### ISSUE TITLE
Flatpak support on JingOS ARM - Fix "bwrap: Can't mount proc on /newroot/proc: Device or resource busy" error

### ISSUE THREAD

**Issue by Maxximo88** [JingOS-team/JingOS#105]
Hi,
on JingPad A1 with JingOS ARM is possible to add Flatpak support following this guide:
https://forum.jingos.com/t/guide-flatpak-app-install-and-use-flatpak/2206

Unfortunately flatpaks are broken too ATM, they fail with the following issue:
bwrap: Can't mount proc on /newroot/proc: Device or resource busy

Please fix it!

**Comment by JingOS-team** [comment]
Flatpak issues will be solved with V1.2
