### ISSUE TITLE
Keyboard Home-Button? (Question / Feature Request)

### ISSUE THREAD

**Issue by Gandalf1783** [JingOS-team/JingOS#121]
**Is your feature request related to a problem? Please describe.**
I cannot exit apps while testing JingOS in a VM. (Alt+F4 works, but always forcefully stops the app)

**Describe the solution you'd like**
Either:
A. A dedicated Shortcuts option in the Settings for defining system-wide shortcuts (Like Back, volume up/down, home button, lock, multitasking)
B. Some kind of close app button in the control center.

**Describe alternatives you've considered**
ALT+F4. Does its job though.

**Additional context**
/

**Comment by PaultheFish** [comment]
Setting shortcuts will come in March.
