### ISSUE TITLE
Drivers: Binary blobs and linux upstreaming?

### ISSUE THREAD

**Issue by risen** [JingOS-team/JingOS#23]
Hello,

The JingPad A1 looks to be a very nice Linux Tablet, but I was wondering what the driver situation will be. Will there be an effort to upstream the driver support patches to the Linux kernel?

It's not very clear what SoC you will be using (MediaTek P90 maybe?), but for example PowerVR usually doesn't provide open Linux drivers.

So what's the open source status of the different drivers (GPU, WiFi, modem etc)? Being stuck on an older kernel would make it useless to me.

**Comment by JingOS-team** [comment]
At present, we only adopt the SoC of JingPad. When we complete the adaptation, we will open-source it to developers to port other Linux systems.
