### ISSUE TITLE
Hardware update: First JingPad A1 Sample Device Hands On Video

### ISSUE THREAD

**Issue by JingOS-team** [JingOS-team/JingOS#25]
These are the first two JingPad A1s from the factory we just received last week. Today, I'm going to take a close look at them. This is the first video that shows what JingPad looks like physically.

[Youtube Video](https://www.youtube.com/watch?v=1qANxJwQPK8)

**Comment by noobkun** [comment]
what is the difference between A1 and C1
JingPad C1 mentioned here
https://forum.jingos.com/t/jingos-roadmap-v1-0-published-on-jan-2021/218
