### ISSUE TITLE
希望JingPad 不要用什么垃圾EMMC, 本来Linux系统可用性就差

### ISSUE THREAD

**Issue by cnmade** [JingOS-team/JingOS#27]
再加上IO 拖慢系统响应，谁来买这种体验的设备呢？

Linux只有在有高速IO加持下，能跑得舒服一点，建议上UFS 3.1及以上，能上NVMe就上NVMe

IO决定了性能表现，现在的CPU，动不动就8核，性能不差了，内存也可以做到16GB，也够了，就是垃圾IO，现在国内平板厂子，一水的EMMC 5.0， 少有的上UFS2.1，也快不到哪里去。

只有UFS 3.1及以上才能一战。

**Comment by edwinhao-yawei** [comment]
感谢建议，我们后面会采纳！
