### ISSUE TITLE
安卓win二合一平板，刷了这个系统后没触屏驱动，怎么解决，能提供一下思路吗

### ISSUE THREAD

**Issue by dingtom** [JingOS-team/JingOS#30]
安卓win二合一平板，刷了这个系统后没触屏驱动，怎么解决，能提供一下思路吗

**Comment by edwinhao-yawei** [comment]
预览版暂时还不支持所有平板，目前只测试了华为Matebook，联想yoga，surface系列，如果没有驱动可能需要自己调试。


------------------ 原始邮件 ------------------
发件人: dingtom ***@***.***&gt;
发送时间: 2021年5月19日 14:21
收件人: JingOS-team/JingOS ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[JingOS-team/JingOS] 安卓win二合一平板，刷了这个系统后没触屏驱动，怎么解决，能提供一下思路吗 (#30)





 
安卓win二合一平板，刷了这个系统后没触屏驱动，怎么解决，能提供一下思路吗
