### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by hunabku94** [JingOS-team/JingOS#35]
https://hk.mikecrm.com/N0wgIm4 is unreachable.

**Comment by JingOS-team** [comment]
It is still work, you can also try below links:
https://drive.google.com/file/d/1nstG1nAvxC4-U5qY_owAcptf_Y8LYTme/view?usp=sharing
https://download.jingos.com/os/JingOS-V0.8.1-ed3d91.iso

**Comment by JingOS-team** [comment]
It still works, you can also try the below links:
https://drive.google.com/file/d/1nstG1nAvxC4-U5qY_owAcptf_Y8LYTme/view?usp=sharing
https://download.jingos.com/os/JingOS-V0.8.1-ed3d91.iso

**Comment by GHNewbiee** [comment]
0.9 download link does not work.

Keep in mind that when you announce a new version and give a download link which does not work, then you disappoint people with all the consequences...

**Comment by GHNewbiee** [comment]
1.Google driver:

https://drive.google.com/file/d/1l2-VMvozA_7DGulSIz8lWF7FMWYqRlYJ/view?usp=sharing

2. Download link: https://download.jingos.com/os/JingOS-V0.9-a25ea3.iso

**Comment by hunabku94** [comment]
Thanks !

 
 

Envoyé: mardi 1 juin 2021 à 16:07
De: "GPT" ***@***.***>
À: "JingOS-team/JingOS" ***@***.***>
Cc: "hunabku" ***@***.***>, "Author" ***@***.***>
Objet: Re: [JingOS-team/JingOS] Can't download (#35)


 

1.Google driver:

https://drive.google.com/file/d/1l2-VMvozA_7DGulSIz8lWF7FMWYqRlYJ/view?usp=sharing


	Download link: https://download.jingos.com/os/JingOS-V0.9-a25ea3.iso
