### ISSUE TITLE
System language not consistent 

### ISSUE THREAD

**Issue by karmameleon** [JingOS-team/JingOS#38]
Language is set to English but terminal output is showing in Chinese and English.

**Comment by PaultheFish** [comment]
Open terminal and type
```
sudo export LANGUAGE=eng_US
sudo apt-get udpate
```

**Comment by PaultheFish** [comment]
Please open the app Kernel, click "Setting" -> "Configure Language" -> choose English 
![image](https://user-images.githubusercontent.com/50411419/131315138-ddce4815-63df-44bf-a275-a00be526c96b.png)
After selecting “English”, click the button "Defaults"
![image](https://user-images.githubusercontent.com/50411419/131315328-65a5de74-c0cf-41b2-911a-275f2b9fba8f.png)
