### ISSUE TITLE
Keyboard input inconsistent

### ISSUE THREAD

**Issue by karmameleon** [JingOS-team/JingOS#39]
Sometimes keyboard works with input and sometimes a strange little intermediate interface pops up and translates. Would be nice if when tap on terminal (for example) keyboard pops up. Also how to completely disable the floating menu thing. Shown in lower right corner.  

![20210614_182100.jpg](https://user-images.githubusercontent.com/71369379/121880158-425e2800-cd40-11eb-9aab-5ab55fb6624c.jpg)

**Comment by akatsukilevi** [comment]
I got quite annoyed with it too
That is the SogouIME
I managed to stop it by replacing the files `/opt/sogou/files/bin/sogouImeService` and `/opt/sogou/files/bin/sogouImeService-watchdog` by empty sh files:
```bash
#!/bin/bash
```
