### ISSUE TITLE
JingPad A1: Indiegogo Campaign Just Started!

### ISSUE THREAD

**Issue by JingOS-team** [JingOS-team/JingOS#40]
Dear JingOS and JingPad followers, 

It is now one year after the formation of JingLing Tech and it's truly been a fantastic yet challenging year!  

We have relentlessly been working on our open-source Linux-based OS, JingOS, and our Linux tablet, the JingPad. JingOS can be downloaded for free for a while now and plenty of people use it already, while it is under continous improvement. 

But during all this time the development of the JingPad was also firmly driven forwards and now is the time that we can finally release it for sale! 

We proudly announce that the sale of the JingPad A1 is about to start on an Indiegogo crowdfunding campaign. Click the purchase link at: 
https://www.indiegogo.com/projects/jingpad-world-s-first-consumer-level-linux-tablet

The JingPad A1 is the first consumer-level Linux tablet in the world. Its powerful **UNISOC Tiger T7510** processor with ARM architecture provides an outstanding performance at a low energy consumption. Fully charged the usage time is 8 to 10 hours. The displays resolution is **2368 x 1728** which **ranges in the top 2%** of the laptops in 2020. The display format of **4:3** means 20% more height compared to 16:10 screens. Its weight is only **490g** and its thickness is 6.7mm, so it can brought anywhere without effort. JingPad A1 comes with a stylus that detects **4096 pressure levels** and thus the drawing is very realistic.
https://www.youtube.com/watch?v=yF_sgYMDKCA 

The JingPad A1 runs JingOS, which is tailored to provide the user an excellent, iPad-like user experience. It features a software framework that can run Android apps virtually natively, thus, on JingPad A1 the user can execute **Android and Linux Apps**.
https://www.youtube.com/watch?v=byEN1AnLC4o 

The JingPad Keyboard is a trackpad-keyboard, which can easily be attached to the tablet. The keyboard has a complete layout and the large **98.5mm x 45.0mm** trackpad allows precise navigation. It supports multi‑touch gestures just like the Apple Magic Trackpad. The JingPad Keyboard turns the JingPad A1 into a fully functional laptop. Thus the JingPad A1 can substitute both an Android tablet and a Linux laptop. 

JingPad A1 can be your future daily driver! It is portable, versatile, and powerful. See you at the Indiegogo crowdfunding campaign! 

Best wishes, 
JingOS and JingPad Team

**Comment by konradybcio** [comment]
Hi, where can I access the Linux kernel source code for the A1?
