### ISSUE TITLE
jing OS on Dell Venue 11 7130

### ISSUE THREAD

**Issue by markosjal** [JingOS-team/JingOS#41]
trying to run jingos on dell venue 11 7130

Impressive looking interface

I have the following issues:

When tablet is rotated to vertical display is upside -down

On screen keyboard occupies excessive vertical space about half of the height of screen in horizontal mode. When tablet rotated vertically keyboard is too wide to display (aside from it also being upside-down)

No support for the wifi nor bluetooth in Dell 7130 . I know this is a linux issue and ordered intel 8260 which might work.

No way to easily shut down from GUI (where is power icon?). I have to go to terminal and do 'sudo shutdown 0'

More info on this 2 in 1 here https://www.studioteabag.com/science/dell-venue-pro-linux/DV11P/

Any hope for getting the keyboard fixed and getting display to rotate correctly?

**Comment by k4ever** [comment]
I have the same rotation issue with a Microsoft Surface Pro 4.
