### ISSUE TITLE
Screen Rotation Upside Down Surface Pro 4

### ISSUE THREAD

**Issue by k4ever** [JingOS-team/JingOS#42]
I'm running JingOS 0.9 on a Core i-5 16 GB RAM Microsoft Surface Pro 4. When I rotate the screen the desktop is upside down. How do I fix this?

**Comment by PaultheFish** [comment]
The potential problem is the driver of the gyro and the solution is to put your device in mirror mode.

**Comment by interstellartaurus** [comment]
Are you running surface linux kernel?
