### ISSUE TITLE
JingOS on 蓝魔 i9s pro

### ISSUE THREAD

**Issue by Bevisy** [JingOS-team/JingOS#43]
通过 liveOS 的方式体验了下 v0.9 版本

适配：
1. 屏幕（手势操作正常）、wifi、蓝牙、声音、音量键、电源按钮 驱动正常

待完善：
1. Install OS APP 打开后，屏幕有效范围只显示语言条部分，无法点击 “Next” 按钮（可能需要支持屏幕分辨率调整）
2. 操作整体较卡顿，相对Lubuntu来说

---
个人体验，供参考

**Comment by JingOS-team** [comment]
感谢反馈，请问你的硬件设备是什么型号的？还有配置？
