### ISSUE TITLE
能否用作小型服务器？

### ISSUE THREAD

**Issue by HWYWL** [JingOS-team/JingOS#48]
是这样的，手头有旧的平板，想做一台小型的低功耗服务器，运行一些Java、Python程序，顺便搭建docker之类的，请问是否支持呢？

**Comment by PaultheFish** [comment]
谢谢您的提问！现阶段JingOS发行版本只有x86构架的，如果说您手上的平板电脑满足x86构架，可以安装并运行Ubuntu的话，那么你可以尝试一下安装JingOS，并将其设置成小型服务器。至于Java和Python的程序支持，安装上相应的runtime就可以了

**Comment by PaultheFish** [comment]
谢谢您的提问！现阶段JingOS发行版本只有x86构架的，如果说您手上的平板电脑满足x86构架，可以安装并运行Ubuntu的话，那么你可以尝试一下安装JingOS，并将其设置成小型服务器。至于Java和Python的程序支持，安装上相应的runtime就可以了

**Comment by PaultheFish** [comment]
谢谢您的提问！现阶段JingOS发行版本只有x86构架的，如果说您手上的平板电脑满足x86构架，可以安装并运行Ubuntu的话，那么你可以尝试一下安装JingOS，并将其设置成小型服务器。至于Java和Python的程序支持，安装上相应的runtime就可以了

**Comment by pekinlcc** [comment]
> 是这样的，手头有旧的平板，想做一台小型的低功耗服务器，运行一些Java、Python程序，顺便搭建docker之类的，请问是否支持呢？

可以的，你可以看下旋律果子UP主做的视频，里面有做测试：
https://www.bilibili.com/video/BV1YQ4y1r7Yq?from=search&seid=15859229900245340774&spm_id_from=333.337.0.0；
https://www.youtube.com/watch?v=ascjRHlCCBk
