### ISSUE TITLE
Support for flutter development

### ISSUE THREAD

**Issue by MohamedAliRashad** [JingOS-team/JingOS#49]
Flutter will accelerate app development  for JingOS and may even allow for a separate app store away from google play.

**Comment by PaultheFish** [comment]
Hello! Flutter is available on Linux devices. If you want to install the SDK, please use terminal and type in 
`sudo snap install flutter --classic`
After this step, use a text editor to bond with the SDK, then you are ready to go!

**Comment by nohkumado** [comment]
come on.... why the additional overhead of snap if you can install the thing directly?? https://github.com/nohkumado/JingOS/blob/main/doc/guide_install_flutter.md
