### ISSUE TITLE
Pin Code at startup on VirtualBox

### ISSUE THREAD

**Issue by NoAccount1** [JingOS-team/JingOS#6]
Hello 

I tried to start JinOS V0.6 downloaded from [this link](https://download.jingos.com/os/JingOS-V0.6.iso) on Oracle VirtualBox but I got this screen with an unknow pin code

![VirtualBox_JingOS_22_03_2021_17_45_47](https://user-images.githubusercontent.com/74969657/112026471-8cb37c80-8b36-11eb-912b-4a3bac1ae4ad.png)

These are my settings on Virtualbox 
![2021-03-22_17h48_35](https://user-images.githubusercontent.com/74969657/112026859-e9169c00-8b36-11eb-80b8-5ee619b3cdb5.png)

**Comment by edwinhao-yawei** [comment]
123456

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："NoAccount1 ***@***.***&gt;;
发送时间：2021年3月23日(星期二) 凌晨0:53
收件人："JingOS-team/JingOS" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[JingOS-team/JingOS] Pin Code at startup on VirtualBox (#6)
-----------------------------------

 

 
Hello
 
I tried to start JinOS V0.6 downloaded from this link on Oracle VirtualBox but I got this screen with an unknow pin code
 

 
These are my settings on Virtualbox
