### ISSUE TITLE
Support surface book 3 ?

### ISSUE THREAD

**Issue by badlee** [JingOS-team/JingOS#61]
This os support MS Surface book 3 ?

**Comment by interstellartaurus** [comment]
Likely not, but that doesn't mean you should not try. Download, install, probably will boot.. Go to surface linux github here: [Surface Linux](https://github.com/linux-surface/linux-surface) and download their custom kernel and try to install. I am on a surface book 1 on Elementary currently and this works fine. JingOS is not yet complete so you will miss quite a bit of functionality while waiting for updates.  I do not know if there is dual boot capability at this time either, if you wanted to keep the windows install beside it.
