### ISSUE TITLE
是否支持联想miix520 PC平板二合一？

### ISSUE THREAD

**Issue by Reraaan** [JingOS-team/JingOS#62]
如题，是否支持联想miix520 PC平板二合一？

**Comment by llinfeng** [comment]
你可以试试烧录一个安装U盘，能从USB设备启动，就是能用。

【但目前的`JingOS V0.9-a25ea3`还不太适合自用——它不能创建自己的用户，也不能给`jingos`这个用户更改密码】

使用完成后，找到它自带的命令行程序（底下的dock里面有个黑黑的图标），执行下面一行命令，可以引导烧录系统镜像到本地磁盘上去
```
sudo -E calamares
```
