### ISSUE TITLE
Possible instalation in a Xperia Tab

### ISSUE THREAD

**Issue by LucasDRavarotto** [JingOS-team/JingOS#7]
Best regards, I would like to consult the possibility of installing the system on a Sony tablet, the Z2 tab. Is it possible that it runs with a Snapdragon 801 processor and being ARM 32 bits?

**Comment by pekinlcc** [comment]
> Best regards, I would like to consult the possibility of installing the system on a Sony tablet, the Z2 tab. Is it possible that it runs with a Snapdragon 801 processor and being ARM 32 bits?

We only have JingOS for x86 by now. Maybe later, the community can help to port the ARM version to Snapdragon tablets.

**Comment by AggamR** [comment]
> > Best regards, I would like to consult the possibility of installing the system on a Sony tablet, the Z2 tab. Is it possible that it runs with a Snapdragon 801 processor and being ARM 32 bits?
> 
> We only have JingOS for x86 by now. Maybe later, the community can help to port the ARM version to Snapdragon tablets.

Any project you know of that's trying to do so? Also, does that mean there is an ARM version?
