### ISSUE TITLE
Unable to uninstall android packages - Jingpad A1

### ISSUE THREAD

**Issue by samytichadou** [JingOS-team/JingOS#74]
Jingpad A1 with JingOS v1.1.0

I am unable to uninstall apk apps currently using "uninstall command", terminal throws me "uninstall failed" without more explanations. I tried with name of the app and name of the package listed through the list command.

**Comment by JingOS-team** [comment]
Hey Tonton! Can you describe this issue in more detail?
1. Which app?
2. Which command?

**Comment by samytichadou** [comment]
Sorry for the delay, i'll try to give you details in the next days, but i basically was not able to uninstall anything with the proper command (from the android app tut from your blog)
