### ISSUE TITLE
Instalation on Teclast x6 pro 

### ISSUE THREAD

**Issue by daverod24** [JingOS-team/JingOS#8]
Greetings, I would like to inquire about the possibility of installing the system on a tablast x6 pro tablet. Is it possible that it works? I tested with Ubuntu 20.04 and it has problems with drivers: the camera, the touchscreen

**Comment by pekinlcc** [comment]
> Greetings, I would like to inquire about the possibility of installing the system on a tablast x6 pro tablet. Is it possible that it works? I tested with Ubuntu 20.04 and it has problems with drivers: the camera, the touchscreen

JingOS is based on Ubuntu 20.04, it should have the same problems.
