### ISSUE TITLE
Battery draining issue while JingPad on standby mode.

### ISSUE THREAD

**Issue by mok888** [JingOS-team/JingOS#85]
Battery draining while JingPad fully charged and put on standby mode.

Condition:
1. 100% charged.
2. Plane mode activated. (Wifi + BT off)

Kindly look into it as this will be a critical requirement for user especially on/ off using the pad.

**Comment by JingOS-team** [comment]
We are optimising this issue at the moment. There might be some significant battery drain when connecting the keyboard or keeping the BT and WIFI on.

**Comment by susanin-ivan** [comment]
Non-stop writting debug info into system log might be source of this issue. Just run "journalctl -f" from terminal - this flood never stops

**Comment by JingOS-team** [comment]
I have assigned this issue to our test team

**Comment by susanin-ivan** [comment]
Usually issue are closed when fix is available. 
Closing performace issue unfixed is a bad habbit and does not adds to your reputation.
